source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
#use_frameworks!

target 'ZBStudy' do
 
     pod 'SnapKit', '~> 5.0.0'
     #pod 'Kingfisher', '~> 5.0'

     
     #pod 'SVProgressHUD'
     #pod "RTRootNavigationController"
    
     #pod 'IQKeyboardManagerSwift'
     
     
     pod 'SwiftDate', '~> 5.0'
     #pod 'SCLAlertView'
  
     pod 'SwiftyJSON', '~> 4.0'
     
     #MVVM RXSwift ,Realm,路由
     pod 'Alamofire'
     pod 'Moya' # 网络
     pod 'ObjectMapper' #模型
     pod 'RxSwift'
     pod 'URLNavigator'#swift 路由
     pod 'RxCocoa'
     
     #组件化 待查找
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end
